[app1]
address = "127.0.0.1:3001"
start = "/Users/frectonz/.nix-profile/bin/bun /Users/frectonz/workspace/pennies/apps/app1.ts"
wait_period = 1000
health_check = "/api/status"

[app2]
address = "127.0.0.1:3002"
start = "/Users/frectonz/.nix-profile/bin/bun /Users/frectonz/workspace/pennies/apps/app2.ts"
wait_period = 1000
health_check = "/api/status"
