[app1]
address = "127.0.0.1:3001"
wait_period = "1m"
health_check = "/api/status"
command = "bun apps/app1.ts"

[app2]
address = "127.0.0.1:3002"
wait_period = "10m"
health_check = "/api/status"

[app2.command]
start = "bun start"
end = "bun end"
