api_address = "127.0.0.1:3031"

["app1.local"]
address = "127.0.0.1:3001"
wait_period = "1m"
health_check = "/api/status"
command = "bun apps/app1.ts"

["app2.local"]
address = "127.0.0.1:3002"
wait_period = "30s"
health_check = "/api/status"

["app2.local".command]
start = "bun apps/app2.ts"
end = "pkill bun"
