name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Flake Check
        run: nix flake check

      - name: Install UI Dependencies
        run: nix develop -c pnpm install --frozen-lockfile
        working-directory: ui

      - name: Check UI Formatting
        run: nix develop -c pnpm check
        working-directory: ui

      - name: Run UI Lint
        run: nix develop -c pnpm lint
        working-directory: ui

      - name: Build UI
        run: nix develop -c pnpm build
        working-directory: ui

      - name: Check Rust Formatting
        run: nix develop -c cargo fmt --check

      - name: Run Rust Clippy
        run: nix develop -c cargo clippy -- -D warnings

      - name: Run Rust Tests
        run: nix develop -c cargo test

      - name: Build Rust Project
        run: nix develop -c cargo build --release
